name: Teste com Ambiente de Produção

on:
  workflow_dispatch:

jobs:
  validar-teste:
    runs-on: windows-latest
    continue-on-error: true
    outputs:
      resultado: ${{ steps.erro.outputs.resultado }}
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Rodar script e capturar erro
        id: erro
        shell: pwsh
        run: |
          python scripts/teste_funcional.py
          if ($LASTEXITCODE -eq 0) {
            echo "resultado=sucesso" >> $env:GITHUB_OUTPUT
          } else {
            echo "resultado=falha" >> $env:GITHUB_OUTPUT
          }

  deploy-automatico:
    needs: validar-teste
    runs-on: windows-latest
    if: ${{ needs.validar-teste.outputs.resultado == 'sucesso' }}
    environment:
      name: producao-auto
    steps:
      - name: Deploy automático
        run: echo "Deploy automático liberado com sucesso."

  deploy-manual:
    needs: validar-teste
    runs-on: windows-latest
    if: ${{ needs.validar-teste.outputs.resultado == 'falha' }}
    environment:
      name: producao
    steps:
      - name: Deploy com aprovação manual
        run: echo "Teste falhou. Aguardando aprovação para deploy manual."
