name: Teste com Ambiente de Produção

on:
  workflow_dispatch:

jobs:
  validar-teste:
    runs-on: windows-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Rodar teste funcional simulado
        id: validacao
        run: python scripts/teste_funcional.py

  deploy-automatico:
    needs: validar-teste
    runs-on: windows-latest
    if: ${{ needs.validar-teste.result == 'success' }}
    environment:
      name: producao
    steps:
      - name: Mensagem de deploy automático
        run: echo "Deploy automático liberado e realizado com sucesso."

  deploy-manual:
    needs: validar-teste
    runs-on: windows-latest
    if: ${{ needs.validar-teste.result == 'failure' }}
    environment:
      name: producao 
    steps:
      - name: Aguardando aprovação manual
        run: echo "Teste funcional falhou. Deploy só será executado após aprovação manual."
